baseurl = "https://alexpax.com"
title = "Alex Pax"
author = "Alex Pax"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Alex Pax"

[[menu.main]]
    name = "Home"
    url = "https://alexpax.com"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/alex-pax"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/alexander-pax-471aa492/"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/AlexPax6"
    weight = 4

